[build-system]
requires = ["setuptools>=68.0.0", "wheel>=0.40.0"]
build-backend = "setuptools.build_meta"

[project]
name = "heart-disease-prediction"
version = "1.0.0"
description = "Heart Disease Risk Assessment Tool"
requires-python = ">=3.11"