[build-system]
requires = ["setuptools>=68", "wheel", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "heart-disease-prediction"
version = "1.0.0"
description = "Heart Disease Risk Assessment Tool"
requires-python = ">=3.11"