services:
  - type: web
    name: heart-disease-api
    env: python
    region: singapore
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn src.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PYTHONPATH
        value: .

  - type: web
    name: heart-disease-frontend
    env: python
    region: singapore
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: streamlit run src/frontend/app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PYTHONPATH
        value: .
      - key: API_URL
        sync: false