services:
  - type: web
    name: heart-disease-api
    env: python
    region: singapore
    python_version: 3.11
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -U setuptools wheel
      pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn src.api.main:app --host 0.0.0.0 --port $PORT